"""add tablearg and Constraint

Revision ID: dfb6c552bb28
Revises: 0f579668724e
Create Date: 2026-01-12 09:42:01.717128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb6c552bb28'
down_revision = '0f579668724e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
