"""add user model

Revision ID: e014ca23734f
Revises: feb8c87155d1
Create Date: 2026-01-11 19:39:54.190902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e014ca23734f'
down_revision = 'feb8c87155d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
