"""2nd migration

Revision ID: feb8c87155d1
Revises: 76435f974b98
Create Date: 2026-01-09 10:58:26.635787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb8c87155d1'
down_revision = '76435f974b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
